### ISSUE TITLE
verify

### ISSUE THREAD

**Issue by abdkaviani** [paydotir/php-sample-code#2]
سلام
من یک نوبت دهی اینترنتی دارم

در متد قبلی که ارائه کرده بودید
زمانی که پس از بازگشت از درگاه بانکی وارد صفحه پذیرنده می شدیم
اطلاعات نظیر شماره پیگیری، شماره کارت، شماره قبض و... به این صفحه «پست» می شدند
اما در روش جدید یک توکن داریم و زمانی که وریفای انجام می دهیم مقادیر فوق یعنی همان شماره پیگیری، کارت، شماره قبض و ... در دسترسی قرار می گیرند

مشکلی که من دارم این است که
در متد قبلی پس از بازگشت از درگاه بانک و قبل از وریفای کردن، من یک بار دیگر ظرفیت نوبت دهی ام را چک می کردم. اگر ظرفیت تمام شده بود، دیگر وریفای را انجام نمی دادم تا پول به حساب واریز کننده برگشت بخورد
در متد جدید من قادر به انجام این کار نیستم ظاهرا !؟

**Comment by saeedvaziry** [comment]
سلام.
توی این متد هم شما میتونید بعد از بازگشت به سایت پذیرنده که توکن ارسال میشه بررسی کنید اگه نوبت همچنان موجود بود وریفای کنید
اگر هم وریفای نکنید مبلغ به حساب پرداخت کنند عودت داده میشه
