### ISSUE TITLE
verify II

### ISSUE THREAD

**Issue by abdkaviani** [paydotir/php-sample-code#3]
سلام مجدد
متشکرم از [پاسخ](https://github.com/paydotir/php-sample-code/issues/2) تون ولی کاش تیکت قبل رو نمی بستید

ببنید تنها زمانی که وریفای انجام شود، من به شماره قبضم دسترسی دارم تا از طریق اون بتونم ظرفیت نوبت دهی اون تاریخ رو چک کنم. اما قبل از وریفای از سمت «پی» چیزی مثل شماره قبض یا متغیر دیگه به جز توکن برام ارسال نمیشه تا این کار رو انجام بدم

مگر از امکاناتی مثل سشن یا کوکی استفاده کنم که به نظرم مناسب نمیاد

**Comment by saeedvaziry** [comment]
شما باید توی دیتابیس خودتون و توی جدول قبض هاتون یه فیلد به اسم توکن بذارید و قبض رو با توکن دریافتی پیدا کنید

**Comment by abdkaviani** [comment]
سپاس
